# Environment shared by every bash and zsh on the MSI Coder devbox. install.sh sources it
# from the top of ~/.bashrc (bash reads that for `ssh devbox '<cmd>'` too) and from
# ~/.zshenv, so it reaches interactive and non-interactive shells alike; agents and the
# VS Code server inherit it from those shells. Keep it POSIX, idempotent, and silent.

# ~/.kube/config is regenerated by the workspace template, so contexts the platform doesn't
# ship (falcon-satx-ca, *-staging, ...) live in a side file. An explicit KUBECONFIG wins.
if [ -n "${CODER_WORKSPACE_NAME:-}" ] && [ -z "${KUBECONFIG:-}" ] \
    && [ -f "$HOME/.kube/extra-contexts.yaml" ]; then
    export KUBECONFIG="$HOME/.kube/config:$HOME/.kube/extra-contexts.yaml"
fi

# yolo tooling (job owners, worktree branch prefixes, telemetry) falls back to $USER,
# which is `coder` on the devbox.
if [ -n "${CODER_WORKSPACE_NAME:-}" ]; then
    export YOLO_USER="${YOLO_USER:-dancrankshaw}"
fi
